### PR TITLE
Update sonarcloud project key

### PR DESCRIPTION
**Pull request by guillaumevillemont**
For https://github.com/element-hq/sre-internal/issues/3184

Signed-off-by: Guillaume Villemont <guillaumev@element.io>

### Pull Request Checklist

- [ ] I read the [contributing guide](https://github.com/element-hq/element-ios/blob/develop/CONTRIBUTING.md).
- [ ] Pull request contains a [changelog label](https://github.com/element-hq/element-x-ios/blob/develop/CONTRIBUTING.md#changelog).
- [ ] Pull request includes a [sign off](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#sign-off).

**UI changes have been tested with:**
- [ ] iPhone and iPad simulators in portrait and landscape orientations.
- [ ] Dark mode enabled and disabled.
- [ ] Various sizes of dynamic type.
- [ ] Voiceover enabled.

### CODE REVIEW

**Review by pixlwave — APPROVED** [review]
Thanks @guillaumevillemont.

**Comment by pixlwave** [comment]
@guillaumevillemont Are we able to migrate our Quality Profile from the old project to the new one? It is missing when I look in the dashboard.

**Comment by guillaumevillemont** [comment]
@pixlwave Ho I'm sorry, I've tried to kept the same settings but I've missed that custom Quality Profile. The old project is now deleted, so it's lost :(

**Comment by pixlwave** [comment]
No worries, we'll take a look at the most common issues in the project, that should probably give us an idea of what we customised 👍

**Pull request merged**
