### PR TITLE
Bump the RustSDK to version 24.12.20

### PR DESCRIPTION
**Pull request by stefanceriu**

### CODE REVIEW

**Review by pixlwave — APPROVED** [review]
I like reviews like this

**Comment by stefanceriu** [comment]
> I like reviews like this

Yeah, why can't they all be like that!? :))

**Comment by stefanceriu** [comment]
> ⚠️	Please provide a description for this PR.

image

**Review by Hywan — APPROVED** [review]
Review was rather complex. Please consider splitting your patches in smaller commits next time.

**Pull request merged**
